name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install cocogitto
        uses: cocogitto/cocogitto-action@v3
        with:
          check: false

      - name: Check conventional commits
        run: cog check --from-latest-tag
